name: Deploy site

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 允许推送到 gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # 选与你的 Gemfile.lock 兼容的版本；你之前用 3.3.5，这里就用 3.3
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build (Jekyll)
        run: |
          export JEKYLL_ENV=production
          bundle install --jobs 4
          bundle exec jekyll build --trace

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          # 如需一并写 CNAME（推荐保留仓库根已有 CNAME 文件即可）
          # cname: jianghao.site
